[package]
name = "rouglike-jrpg"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18"
game = { path = "crates/game" }
ui = { path = "crates/ui" }
rand = "0.8"

[dev-dependencies]
rand_chacha = "0.3"

[workspace]
members = ["crates/game", "crates/ui", "crates/generate_tiles"]
