[package]
name = "field-menu-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18"
rand = "0.8"
party = { path = "../party" }
spell = { path = "../spell" }
app-state = { path = "../app-state" }
input-ui = { path = "../input-ui" }
hud-ui = { path = "../hud-ui" }
