[package]
name = "hokora-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18"
party = { path = "../party" }
app-state = { path = "../app-state" }
input-ui = { path = "../input-ui" }
movement-ui = { path = "../movement-ui" }
