[package]
name = "hokora-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18"
item = { path = "../item" }
party = { path = "../party" }
app-state = { path = "../app-state" }
input-ui = { path = "../input-ui" }
field-core = { path = "../field-core" }
hud-ui = { path = "../hud-ui" }
