[package]
name = "town-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18"
town = { path = "../town" }
app-state = { path = "../app-state" }
shared-ui = { path = "../shared-ui" }
movement-ui = { path = "../movement-ui" }
