[package]
name = "field-walk"
version = "0.1.0"
edition = "2024"

[dependencies]
terrain = { path = "../terrain" }
world-gen = { path = "../world-gen" }
rand = "0.8"

[dev-dependencies]
rand_chacha = "0.3"
